# Generated by Django 4.2.6 on 2023-11-17 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateofCompletion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
