# Generated by Django 4.2.6 on 2023-11-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_dateofcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_gen_ai',
            field=models.BooleanField(default=False),
        ),
    ]
