# Generated by Django 4.2.6 on 2023-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_eligible_for_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pathwaycompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='size',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sized_entered',
            field=models.BooleanField(default=False),
        ),
    ]
