# Generated by Django 4.2.6 on 2023-11-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_pathwaycompleted_student_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
